#!/bin/bash

test () {
    bulk
    python run_tests.py
}

bulk () {
    curl -XDELETE 'http://localhost:1980/_all'; echo
    curl -s -XPOST 'http://localhost:1980/_bulk?refresh=true' --data-binary @tornadoes/tests/data/materias.bulk; echo
    curl -s -XPOST 'http://localhost:1980/_bulk?refresh=true' --data-binary @tornadoes/tests/data/outrasmaterias.bulk; echo
}

if [ $1 ]; then
    $1;
else
    echo  "   bulk - Insert test data into elasticsearch."
    echo  "   test - Run the tests."
    exit 1
fi;
